#ifndef _INCLUDE_GUARD_DATA_SHADERS_INCLUDES_NBLIGHTS_HPP_
#define _INCLUDE_GUARD_DATA_SHADERS_INCLUDES_NBLIGHTS_HPP_



#define MAX_NB_DIRECTIONAL_LIGHT 0
#define MAX_NB_POINT_LIGHT 4
#define MAX_NB_SPOT_LIGHT 0



#endif // ___INCLUDE_GUARD_DATA_SHADERS_INCLUDES_NBLIGHTS_HPP___

